### ISSUE TITLE
Static link ?

### ISSUE THREAD

**Issue by DanRZ** [tbattz/iracingOverlay#2]
Is it possible to link statically the iracingOverlay.exe ?
I need to add freetype.dll, libgcc_s_seh-1.dll, libstdc++-6.dll and libwinpthread-1.dll next to the exe to make it work.
Is it normal ?
It would be cool if the iracingOverlay.exe could work alaone.

**Comment by tbattz** [comment]
It might be able to. Most of the setup for the OpenGL part of the code comes from what I did with the openGLPlotLive repo (see https://github.com/tbattz/openGLPlotLive), which originally was developed for Linux, and then adjusted to get working on windows. I had a heap of trouble getting the libraries to play nice on windows compared to Linux, I think there may have been some issue with static linking to freetype on windows, though there may have also been other issues.

Are you compiling/running in an IDE or on command line? In CLion or the windows command prompt, it should compile and run just fine without needed to add those, provided cmake has worked correctly.

**Comment by DanRZ** [comment]
I'm compiling with CMake in command line ... Maybe i will try CLion. Is it free ?
I have some trouble with linking library but it works fine with some tweaks (Mostly in openGLPlotLive).
I use some specific paths, my User's Doucments is in another disk than C: and it creates some weird behaviors i think.
Blanks on paths are not well used i think ...
I will probably add everything needed on a drive to avoid those kind of troubles.

I'm thinking of using your App to record the better braking/throttle curve to help driver see if its last brake/throttle is better or worst, by displaying it added to the "live" values ... The Delta you added makes the same effect but is less comprehensive.

You can close this Issue, which was more a question than a real Issue.

Thanks for the answer.

**Comment by tbattz** [comment]
CMake and command line should still work, though I might have something else set in my path without realising it. Looking here though https://stackoverflow.com/questions/18138635/mingw-exe-requires-a-few-gcc-dlls-regardless-of-the-code, check if you've added the following to your PATH variable: https://github.com/tbattz/iracingOverlay/blob/master/Installers/installDependiciesWindows-part1.bat#L83

Oh cool, that shouldn't be too hard to add, since most of the structure for it is there, let me know how it goes. I'll close this issue then.

**Comment by DanRZ** [comment]
Thanks. I read the post tou linked and think it's probably due to linking freetype as a dll that itself link to shared libraries/dlls ...
I saw you made some modifications to add the static library for freetype. That will probably solve the problem.
CMake linker seems to analyse which lib he use when you add only the name and not the full path.
If you link "freetype" only (and adding link_directories), it will try to find patterns like libfreetype.a, freetype.lib, freetype.dll and link with the one he founds ... That's what i noticed.
In your CMake you added the full path to libs like freetype, glfw3, ... and that's probably not a good way to do it. Add the library "short" name to your list and add the directory to CMake linker ... as it's done for opengl32 for example.
All linked libs should be used with same rules ...

I'm an old developer and discover GitHub. I will probably send you some other issues and probably some pull requests for minor updates i see ...
If you don't mind ? 😉

You did a really nice work on this project and its dependencies.

I will try the very last version on master and see if i can link statically all libs. I need to reinstall properly everything and especially the freetype lib ...

**Comment by tbattz** [comment]
No worries, I think initially when I was just learning the openGL side, I had it setup with just the name and not full path, and ended up with a heap of problems with it picking up different versions of the lib in different locations. Generally it was just a headache, so I set it to the full path, not intending for it to really be used elsewhere. That was back on a different repository, in which I used the oepnGL setup as a starting point for a bunch of other repositories a few years later, and didn't revisit the original setup.

Sure, what you could do, is 'fork' the repository (see https://docs.github.com/en/github/getting-started-with-github/fork-a-repo), so that you have a version of it that you can edit and upload. Then do a pull request with any useful changes (see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) and if it all works well I'll pull them back into this original repo. This might also be useful if you're new  to github for contributing back (https://www.dataschool.io/how-to-contribute-on-github/ and https://gist.github.com/Chaser324/ce0505fbed06b947d962)

Thanks, I wasn't that experienced with c++ when I wrote most of this, so there might be some bits that are a little messy (excuse the hardcoding of the telemetry file for testing..., I never really expected anyone to actually look at the code). 

My IRacing subscription has expired, so I can't do a lot of testing other than existing telemetry files, so I'm unlikely to be adding more to it, but I'll pull any changes you make that make it better/more maintainable into the main repo.

As a side note, the freetype library is for text rendering in openGL, which the throttleBrackTrace doesn't actually use, but the openGLPlotLive repository does. So... it's still probably easier to install freetype so that openGLPlotLive can be compiled, rather than removing it from openGLPlotLive itself. Originally I was going to add red/purple running text for the time gained in a corner, displaying at corner exit. But it turned out a bit too distracting and didn't really work that well, so was abandoned. Though I think the half finished track map might require freetype, I'm not entirely sure.
